version: '3.7'

networks:
  datastack:
    driver: bridge

services:
  ##############################################################################
  # Core Services (Redis, Postgres)
  ##############################################################################
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    env_file: docker/docker.env
    volumes:
      - ./docker/postgres_init:/docker-entrypoint-initdb.d
      - ./_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  redis:
    image: redis:latest
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

volumes:
  redis:
    external: false

